<a href="https://colab.research.google.com/github/SLCFLAB/Data-Science-Python/blob/main/Day%205/5_2.Numerical%20Linear%20Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1장 Matrix Computation

#### 코드 출처 
[1] https://github.com/rickiepark/machine-learning-with-python-cookbook

[2] https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html https://colab.research.google.com/github/SLCFLAB/Math4DS/blob/main

# 2절 Numerical Linear Algebra

## 2.1 행렬의 랭크 구하기

In [ ]:
# 라이브러리를 임포트합니다.
import numpy as np

# 행렬을 만듭니다.
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# 행렬의 랭크를 반환합니다.
np.linalg.matrix_rank(matrix)

2

### 붙임

In [ ]:
# 2D 배열이므로 2가 반환됩니다.
np.ndim(matrix)

2

In [ ]:
# svd 함수로 특잇값만 계산합니다.
s = np.linalg.svd(matrix, compute_uv=False)
# 오차를 고려하여 0에 가까운 아주 작은 값을 지정합니다.
np.sum(s > 1e-10)

2

In [ ]:
# Todo
# pdf 17페이지에 나와있는 A,B 행렬의 rank 구해보기


## 2.2 행렬식(determinant)과 norm 계산하기

In [ ]:
# 라이브러리를 임포트합니다.
import numpy as np
from scipy import linalg

# 행렬을 만듭니다.
A = np.array([[1, 3, 5],
              [2, 5, 1],
              [2, 3, 8]])

# 행렬의 행렬식을 반환합니다.
linalg.det(A)

-25.000000000000004

In [ ]:
linalg.norm(A)

11.916375287812984

In [ ]:
linalg.norm(A,'fro') # frobenius norm is the default

11.916375287812984

In [ ]:
linalg.norm(A,1) # L1 norm (max column sum)

14.0

In [ ]:
linalg.norm(A,-1) # min column sum

5.0

In [ ]:
linalg.norm(A,np.inf) # L inf norm (max row sum)

13.0

In [ ]:
# Todo
# pdf p.23 문제 numpy package로 구해보기


## 2.3 행렬의 대각 원소 추출하기

In [ ]:
# 라이브러리를 임포트합니다.
import numpy as np

# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# 대각 원소를 반환합니다.
matrix.diagonal()

array([1, 4, 9])

### 붙임

In [ ]:
# 반환된 배열을 변경하려면 복사해야 합니다.
a = matrix.diagonal().copy()

In [ ]:
a = np.diag(matrix)
print(a)

[1 4 9]


In [ ]:
# 1차원 배열이 주어지면 2차원 대각행렬을 만듭니다.
np.diag(a)

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

## 2.4 행렬의 대각합(trace) 계산

In [ ]:
# 라이브러리를 임포트합니다.
import numpy as np

# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# 대각합을 반환합니다.
matrix.trace()

14

In [ ]:
# 대각 원소를 사용하여 합을 구합니다.
sum(matrix.diagonal())

14

## 2.5 점곱 계산

In [ ]:
# 라이브러리를 임포트합니다.
import numpy as np

# 두 벡터를 만듭니다.
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# 점곱을 계산합니다.
np.dot(vector_a, vector_b)

32

### 붙임

In [ ]:
scalar_a = np.array(1)
scalar_b = np.array(2)

In [ ]:
np.dot(scalar_a, scalar_b)

2

In [ ]:
# 스칼라 배열에 적용되지 않습니다.
scalar_a @ scalar_b

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

## 2.6 행렬 덧셈과 뺄셈

In [ ]:
# 라이브러리를 임포트합니다.
import numpy as np

# 행렬을 만듭니다.
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# 행렬을 만듭니다.
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# 두 행렬을 더합니다.
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [ ]:
# 두 행렬을 뺍니다.
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [ ]:
# 두 행렬을 더합니다.
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## 2.7 행렬 곱셈

In [ ]:
# 라이브러리를 임포트합니다.
import numpy as np

# 행렬을 만듭니다.
matrix_a = np.array([[1, 1],
                     [1, 2]])

# 행렬을 만듭니다.
matrix_b = np.array([[1, 3],
                     [1, 2]])

# 두 행렬을 곱합니다.
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [ ]:
# 두 행렬을 곱합니다.
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [ ]:
# 두 행렬의 원소별 곱셈을 수행합니다.
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

## 2.8 역행렬 구하기, 연립방정식 풀기

In [ ]:
import numpy as np
from scipy import linalg
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [ ]:
linalg.inv(A)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [ ]:
A.dot(linalg.inv(A)) #double check

array([[ 1.00000000e+00, -1.11022302e-16,  4.85722573e-17],
       [ 3.05311332e-16,  1.00000000e+00,  7.63278329e-17],
       [ 2.22044605e-16, -1.11022302e-16,  1.00000000e+00]])

In [ ]:
# 행렬과 역행렬을 곱합니다.
A @ np.linalg.inv(A)

array([[ 1.00000000e+00,  1.11022302e-16, -6.24500451e-17],
       [-1.38777878e-16,  1.00000000e+00, -1.45716772e-16],
       [-2.22044605e-16,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
b = np.array([[10], [8], [3]])
b

array([[10],
       [ 8],
       [ 3]])

In [ ]:
linalg.inv(A).dot(b)

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [ ]:
A.dot(linalg.inv(A).dot(b)) - b  # check

array([[ 0.00000000e+00],
       [-1.77635684e-15],
       [-8.88178420e-16]])

In [ ]:
np.linalg.solve(A, b)  # fast

array([[-9.28],
       [ 5.16],
       [ 0.76]])

## 2.9 Eigenvalues and eigenvectors & SVD

In [ ]:
import numpy as np
from scipy import linalg
A = np.array([[1, 5, 2], [2, 4, 1], [3, 6, 2]])
la, v = linalg.eig(A)
l1, l2, l3 = la
print(l1,l2,l3)

(7.957916204910748+0j) (-1.2576647056775332+0j) (0.2997485007667829+0j)


In [ ]:
print(v[:, 0]) 
print(v[:, 1]) 
print(v[:, 2]) 

[-0.5297175  -0.44941741 -0.71932146]
[-0.90730751  0.28662547  0.30763439]
[ 0.28380519 -0.39012063  0.87593408]


In [ ]:
import numpy as np
from scipy import linalg
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
M,N = A.shape
U,s,Vh = linalg.svd(A)
Sig = linalg.diagsvd(s,M,N)
U.shape,  s.shape, Vh.shape

((2, 2), (2,), (3, 3))

In [ ]:
U

array([[-0.3863177 , -0.92236578],
       [-0.92236578,  0.3863177 ]])

In [ ]:
Sig

array([[9.508032  , 0.        , 0.        ],
       [0.        , 0.77286964, 0.        ]])

In [ ]:
Vh

array([[-0.42866713, -0.56630692, -0.7039467 ],
       [ 0.80596391,  0.11238241, -0.58119908],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [ ]:
U.dot(Sig.dot(Vh)) #check computation

array([[1., 2., 3.],
       [4., 5., 6.]])

## 2.10 난수 생성

In [ ]:
# 라이브러리를 임포트합니다.
import numpy as np

# 초깃값을 지정합니다.
np.random.seed(0)

# 0.0과 1.0 사이에서 세 개의 실수 난수를 생성합니다.
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [ ]:
# 1과 10 사이에서 세 개의 정수 난수를 생성합니다.
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [ ]:
# 평균이 0.0이고 표준 편차가 1.0인 정규 분포에서 세 개의 수를 뽑습니다.
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [ ]:
# 평균이 0.0이고 스케일이 1.0인 로지스틱 분포에서 세 개의 수를 뽑습니다.
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [ ]:
# 1.0보다 크거나 같고 2.0보다 작은 세 개의 수를 뽑습니다.
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])

### 붙임

In [ ]:
# 0.0(포함)과 1.0 사이에서 세 개의 실수 난수를 생성합니다.
# np.random.random((2, 3)), np.random.sample((2, 3)), 
# np.random.uniform(0.0, 1.0, (2, 3))과 동일합니다.
np.random.random_sample((2, 3))

array([[0.33739616, 0.64817187, 0.36824154],
       [0.95715516, 0.14035078, 0.87008726]])

In [ ]:
# np.random.random_sample((2, 3))과 동일합니다.
np.random.rand(2, 3)

array([[0.47360805, 0.80091075, 0.52047748],
       [0.67887953, 0.72063265, 0.58201979]])

In [ ]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# np.random.normal(0.0, 1.0, (2, 3))과 동일합니다.
np.random.standard_normal((2, 3))

array([[-0.13309028,  1.59456053,  0.23043417],
       [-0.06491034, -0.96898025,  0.59124281]])

In [ ]:
# np.random.normal(0.0, 1.0, (2, 3))과 동일합니다.
np.random.randn(2, 3)

array([[-0.7827755 , -0.44423283, -0.34518616],
       [-0.88180055, -0.44265324, -0.5409163 ]])

In [ ]:
# 0~2 사이의 정수 중 랜덤하게 10번을 뽑습니다.
# np.random.choice(3, 5)와 동일합니다.
np.random.choice([0,1,2], 5)

array([0, 1, 2, 2, 0])

In [ ]:
a = np.array([0, 1, 2, 3, 4])
np.random.shuffle(a)
a

array([0, 2, 3, 4, 1])

In [ ]:
# a는 변경되지 않습니다.
np.random.permutation(a)

array([2, 0, 1, 3, 4])

In [ ]:
np.random.permutation(5)

array([4, 1, 2, 0, 3])