<a href="https://colab.research.google.com/github/SLCFLAB/Data-Science-Python/blob/main/Day%206/6_1.%20Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ref: https://github.com/Harry24k/Pytorch-Basic

# How to use Colab?


Colaboratory is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

With Colaboratory you can write and execute code, save and share your analyses, and access powerful computing resources, all for free from your browser.

Advantages

- The best thing is that it is free!
- It gives you costly GPUs and working envriornment, independent of what personal machine you are using.
- It also runs on Google servers using virtual machines and you don’t need to install any packages, which sometimes create difficulty you are using different operating systems such as MAC, Windows, and Linux.

### Hotkeys (change as you want)

| hotkey | action |
| --- | --- |
| ctrl + M H | Open hotkey configuration |
| ctrl + O | Open note |
| ctrl + S | Save note |
| ctrl + F9 | Run all cells |
| ctrl + shift + enter | Run cell |
| shift + enter | Run cell and move on to the next |
| alt + enter | Run cell and add a new one below |
| ctrl + M I | Stop running execution |
| ctrl + M A | Add new code cell above |
| ctrl + M B | Add new code cell below |
| ctrl + M D | Delete cell |
| ctrl + M K | Move cell up |
| ctrl + M J | Move cell down |
| ctrl + M Y | Change to code cell |
| ctrl + M M | Change to markdown cell |
| ctrl + M Z | Undo last cell execution |
| ctrl + H | Search |
| ctrl + / | Comment out or undo |

### Terminal commands

In [ ]:
# Get OS info
!cat /etc/issue.net

Ubuntu 18.04.5 LTS


In [ ]:
# Get CPU info
!cat /proc/cpuinfo | grep 'processor\|model name\|cpu cores'
# Get memory info
!free -h
# Get disk info
!df -h

processor	: 0
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
cpu cores	: 1
processor	: 1
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
cpu cores	: 1
              total        used        free      shared  buff/cache   available
Mem:            12G        536M        9.9G        1.2M        2.2G         11G
Swap:            0B          0B          0B
Filesystem      Size  Used Avail Use% Mounted on
overlay          69G   38G   32G  55% /
tmpfs            64M     0   64M   0% /dev
tmpfs           6.4G     0  6.4G   0% /sys/fs/cgroup
shm             5.8G     0  5.8G   0% /dev/shm
/dev/sda1        76G   42G   35G  55% /opt/bin/.nvidia
tmpfs           6.4G   36K  6.4G   1% /var/colab
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware


In [ ]:
# Get GPU info
!nvidia-smi

Sun Aug 22 10:41:23 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Get python version
!python --version

Python 3.7.11


In [ ]:
# Get current directory
!pwd
%cd

/content
/root


In [ ]:
# Get files/folders list
!ls -lah

total 64K
drwx------ 1 root root 4.0K Aug 22 10:28 .
drwxr-xr-x 1 root root 4.0K Aug 22 10:27 ..
-r-xr-xr-x 1 root root 1.2K Jan  1  2000 .bashrc
drwxr-xr-x 1 root root 4.0K Aug 18 13:21 .cache
drwxr-xr-x 1 root root 4.0K Aug 18 13:19 .config
drwxr-xr-x 3 root root 4.0K Aug 17 13:20 .gsutil
drwxr-xr-x 1 root root 4.0K Aug 18 13:19 .ipython
drwx------ 2 root root 4.0K Aug 18 13:19 .jupyter
drwxr-xr-x 2 root root 4.0K Aug 22 10:28 .keras
drwx------ 1 root root 4.0K Aug 18 13:19 .local
drwxr-xr-x 4 root root 4.0K Aug 18 13:19 .npm
-rw-r--r-- 1 root root  148 Aug 17  2015 .profile
-r-xr-xr-x 1 root root  254 Jan  1  2000 .tmux.conf


In [ ]:
!mv
!cp

mv: missing file operand
Try 'mv --help' for more information.
cp: missing file operand
Try 'cp --help' for more information.


In [ ]:
!pip show torch

Name: torch
Version: 1.9.0+cu102
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.7/dist-packages
Requires: typing-extensions
Required-by: torchvision, torchtext, fastai


### File I/O

In [ ]:
# Upload file to Colab workspace
# [NOTE] Uploaded files will be gone when runtime resets
import os
from google.colab import files

uploaded = files.upload()

for f in uploaded.keys():
    print('User uploaded file "{}" at "{}"'.format(f, os.getcwd()))

# Or simply open file tab then drag-and-drop

In [ ]:
# Download file from Colab workspace
# [NOTE] Enable third party cookies and use Chrome browser
files.download('./sample_data/mnist_train_small.csv')

# Or simply open file tab and right click a file then download <-- Recommended

FileNotFoundError: ignored

In [ ]:
# Mount Google drive
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


# 1. Tensor

In [1]:
import torch

In [2]:
print(torch.__version__)

1.4.0


## 1.1 Tensor Basic

In [3]:
#Tensor의 기초적 선언
#torch.FloatTensor와 같음
# x = torch.Tensor(행, 열)
x = torch.Tensor(2, 3)
print(x)

tensor([[5.5729e+32, 8.7861e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
#Tesnor의 정보 확인
print("Tensor Type : ", type(x))
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size()) # x.shape

Tensor Type :  <class 'torch.Tensor'>
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


## 1.2 Tensor with characteristics

In [5]:
#0으로 채워진 Tensor 선언
x = torch.zeros(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [6]:
x = torch.zeros(2,3, dtype=torch.int32)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


In [7]:
#1로 채워진 Tensor 선언
x = torch.ones(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [8]:
#0, 1 사이의 랜덤 숫자로 채워진 Tensor 선언
x = torch.rand(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0.2038, 0.8930, 0.0199],
        [0.4733, 0.0485, 0.4502]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [9]:
#평균이 0이고 분산이 1을 따르는 정규분포에서 추출된 값으로 채워진 Tensor 선언
x = torch.randn(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[-1.5146,  0.1675,  0.2127],
        [-0.1943,  1.0772, -2.1785]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [10]:
#정방행렬과 같은 Tensor 선언
x = torch.eye(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 0., 0.],
        [0., 1., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [11]:
#0부터 2까지 0.5씩 증가하는 Tensor 선언
x = torch.arange(0, 2, step=0.5)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([0.0000, 0.5000, 1.0000, 1.5000])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([4])


In [12]:
#직접 값을 입력하여 선언
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [13]:
#32-bit floating point
x = torch.FloatTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [14]:
#32-bit integer (signed)
x = torch.IntTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[ 929181029, 1647129136, 1717842739],
        [ 809067061,  778385250, 1952543859]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


## 1.3 Tensor and Numpy

In [15]:
import numpy as np

In [16]:
#numpy 형식의 배열
x = np.array([[1,2,3],[1,2,3]])
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [17]:
#numpy를 tensor로 변환
x = torch.from_numpy(x) # x = torch.Tensor(x)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


In [18]:
#tensor를 numpy로 변환
x = x.numpy()
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


## 1.4 Tensor Slicing

In [19]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [20]:
#모든 원소 출력
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [21]:
#2행부터 출력
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [22]:
#2열부터 출력
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.]])

In [23]:
#2행, 2열부터 3열까지 출력
x[1:, 1:3]

tensor([[ 6.,  7.],
        [10., 11.]])

In [24]:
#1행 출력
x[0, :]

tensor([1., 2., 3., 4.])

In [25]:
#x를 1행씩 잘라서 배열로 저장
x_rows = torch.split(x, split_size_or_sections=1, dim=0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [26]:
#x를 2열씩 잘라서 배열로 저장
x_cols = torch.split(x, split_size_or_sections=2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [27]:
#위와 같은 결과
torch.chunk(x, chunks=2, dim=1)

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]), tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

In [28]:
#x_cols의 첫번째 배열 중 특정 부분만 추출하기
torch.masked_select(x_cols[0], torch.BoolTensor([[0,1],[1,0],[0,1]]).bool())

tensor([ 2.,  5., 10.])

## 1.5 Tensor Merging

In [29]:
#x_rows를 행으로 이어 붙이기
torch.cat(x_rows, dim=0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [30]:
#x_rows를 열로 이어 붙이기
torch.cat(x_rows, dim=1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [31]:
#x_cols를 쌓아올리기
x_new = torch.stack(x_cols, dim=0)
print(x_new)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])


## 1.6 Tensor Reshaping

In [32]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [33]:
#4행 3열로 바꾸기
x.view(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [34]:
#2열로 바꾸기
x.view(-1, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [35]:
x.view(2, 1, -1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

In [36]:
#차원이 1인 값을 축소
x.view(2, 1, -1).squeeze()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [37]:
#dim=1 자리에 차원을 추가
x.view(2, 1, -1).squeeze().unsqueeze(dim=1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

## 1.7 Tensor Calculation

In [38]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [39]:
# x와 y의 합
z = torch.add(x, y)
print("z :", z)
print("x+y :", x+y)

z : tensor([[2., 3., 4.],
        [6., 7., 8.]])
x+y : tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [40]:
# x의 모든 원소에서 2를 뺌
print(x - 2)

# x의 모든 원소에 2를 곱함
print(2*x)

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [41]:
#x의 원소와 y의 원소를 각각 곱함
z = torch.mul(x, y)
print("z :", z)
print("x*y :", x*y)

z : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])
x*y : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [42]:
#x의 원소를 각각 제곱함
z = torch.pow(x, 2)
print("z :", z)
print("x**2 :", x**2)

z : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
x**2 : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [43]:
#x의 원소에 log를 씌움
z = torch.log(x)
print("z :", z)
print("x.log() :", x.log())

z : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
x.log() : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [44]:
#x의 원소에 루트를 씌움
z = torch.sqrt(x)
print("z :", z)
print("x.sqrt() :", x.sqrt())

z : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
x.sqrt() : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


In [45]:
#x의 원소에 나머지(mod) 계산
z = x % 2
print(z)

tensor([[1., 0., 1.],
        [0., 1., 0.]])


In [46]:
#x에 절댓값
z = torch.abs(x)
print("z :", z)
print("x.abs() :", x.abs())

z : tensor([[1., 2., 3.],
        [4., 5., 6.]])
x.abs() : tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 1.8 Tensor Casting

In [47]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [48]:
x.type(torch.DoubleTensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [49]:
x.double()

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [50]:
x.type(torch.IntTensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [51]:
x.int()

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## 1.9 Tensor Statistic

In [52]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [53]:
print("x의 합 :", x.sum())
print("x의 최대값 :", x.max())
print("x의 최소값 :", x.min())
print("x의 분산 :", x.var())

x의 합 : tensor(3.)
x의 최대값 : tensor(6.)
x의 최소값 : tensor(-5.)
x의 분산 : tensor(17.9000)


In [54]:
# Scalar Tensor
x.sum().size()

torch.Size([])

In [55]:
# item의 활용
print("x의 합 :", x.sum().item())
print("x의 최대값 :", x.max().item())
print("x의 최소값 :", x.min().item())
print("x의 분산 :", x.var().item())

x의 합 : 3.0
x의 최대값 : 6.0
x의 최소값 : -5.0
x의 분산 : 17.899999618530273


In [56]:
#행(dim=0)을 기준으로 열의 최댓값을 출력
value, index = x.max(dim=0)
value, index

(tensor([4., 2., 6.]), tensor([1, 0, 1]))

In [57]:
#열(dim=1)을 기준으로 행의 최댓값을 출력
value, index = x.max(dim=1)
value, index

# torch.max(x, dim=1)과 같은 결과
# 이는 추후에 계속 등장하므로 매우 중요!

(tensor([2., 6.]), tensor([1, 2]))

In [58]:
#열(dim=1)을 기준으로 각 행을 정렬
value, index = x.sort(dim=1)
value

tensor([[-3., -1.,  2.],
        [-5.,  4.,  6.]])

## 1.10 Tensor *_like function

In [59]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [60]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [61]:
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [62]:
y = torch.rand_like(x)
print(y)

tensor([[0.1168, 0.6319, 0.0703],
        [0.1896, 0.7902, 0.7531]])


## 1.11 Tensor for GPU

In [63]:
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)

tensor([[1., 2., 3.],
        [1., 2., 3.]])


In [64]:
# cuda 확인
print("현재 Cuda 사용 가능한 Device 개수 :", torch.cuda.device_count())
print("현재 Cuda 사용 가능 여부 :", torch.cuda.is_available())
print("현재 사용 중인 Cuda Device :", torch.cuda.current_device())
print("현재 Cuda Device 이름 :", torch.cuda.get_device_name(0))
print("현재 Cuda Device의 사용 가능한 메모리 :", torch.cuda.max_memory_allocated(device=0), "bytes")
print("현재 Cuda Device의 사용 중인 메모리 :", torch.cuda.memory_allocated(device=0), "bytes")

현재 Cuda 사용 가능한 Device 개수 : 1
현재 Cuda 사용 가능 여부 : True
현재 사용 중인 Cuda Device : 0
현재 Cuda Device 이름 : GeForce RTX 2080
현재 Cuda Device의 사용 가능한 메모리 : 0 bytes
현재 Cuda Device의 사용 중인 메모리 : 0 bytes


In [65]:
# cuda 세팅
torch.cuda.set_device(0)

In [66]:
#cpu를 gpu로 전환
gpu_x = x.cuda()
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]], device='cuda:0')
Tensor Type :  torch.cuda.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [67]:
#cpu를 gpu로 전환 2
device = torch.device("cuda")
gpu_x = x.to(device)
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]], device='cuda:0')
Tensor Type :  torch.cuda.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [68]:
#gpu를 cpu로 전환
x = gpu_x.cpu()
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [69]:
#gpu를 cpu로 전환 2
device = torch.device("cpu")
x = gpu_x.to(device)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [70]:
# gpu tensor와 cpu tensor의 연산
gpu_x + x

RuntimeError: expected device cuda:0 but got device cpu

## 1.12 Tensor Calculation as Matrix (참고)

In [71]:
x = torch.Tensor([[1,1],[2,2]])
y = torch.Tensor([[1,2],[3,4]])
print("x :", x)
print("y :", y)

x : tensor([[1., 1.],
        [2., 2.]])
y : tensor([[1., 2.],
        [3., 4.]])


In [72]:
#x와 y의 행렬곱
torch.mm(x, y)

tensor([[ 4.,  6.],
        [ 8., 12.]])

In [73]:
#x와 z의 행렬벡터곱
z = torch.Tensor([1, 2])
torch.mv(x, z)

tensor([3., 6.])

In [74]:
#z와 z의 내적
torch.dot(z, z)

tensor(5.)

In [75]:
#x의 전치(transpose)
x.t()

tensor([[1., 2.],
        [1., 2.]])

In [76]:
# y의 역행렬(inverse)
y.inverse()

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

In [77]:
# 텐서의 배치 행렬곱
x1 = torch.FloatTensor(3,3,2)
x2 = torch.FloatTensor(3,2,3)

torch.bmm(x1,x2).size()

torch.Size([3, 3, 3])

In [78]:
x1

tensor([[[8.4490e-39, 1.0102e-38],
         [9.0919e-39, 1.0102e-38],
         [8.9082e-39, 8.4489e-39]],

        [[9.6429e-39, 8.4490e-39],
         [9.6429e-39, 9.2755e-39],
         [1.0286e-38, 9.0919e-39]],

        [[8.9082e-39, 9.2755e-39],
         [8.4490e-39, 1.0194e-38],
         [9.0919e-39, 8.4490e-39]]])

In [79]:
# 텐서의 전치
x1.transpose(0,2)

tensor([[[8.4490e-39, 9.6429e-39, 8.9082e-39],
         [9.0919e-39, 9.6429e-39, 8.4490e-39],
         [8.9082e-39, 1.0286e-38, 9.0919e-39]],

        [[1.0102e-38, 8.4490e-39, 9.2755e-39],
         [1.0102e-38, 9.2755e-39, 1.0194e-38],
         [8.4489e-39, 9.0919e-39, 8.4490e-39]]])

In [80]:
eigenvalue, eigenvector = torch.eig(x,eigenvectors=True)
print("eigenvalue :", eigenvalue)
print("eigenvector :", eigenvector)

eigenvalue : tensor([[1.1921e-07, 0.0000e+00],
        [3.0000e+00, 0.0000e+00]])
eigenvector : tensor([[-0.7071, -0.4472],
        [ 0.7071, -0.8944]])


In [81]:
#행렬의 QR factorization
Q,R = torch.qr(x)
print("Q :", Q)
print("R :", R)

Q : tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]])
R : tensor([[-2.2361e+00, -2.2361e+00],
        [ 0.0000e+00,  7.3940e-08]])


In [82]:
#행렬의 SVD factorization
S,V,D = torch.svd(x)
print("S :", S)
print("V :", V)
print("D :", D)

S : tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]])
V : tensor([3.1623e+00, 5.2283e-08])
D : tensor([[-0.7071, -0.7071],
        [-0.7071,  0.7071]])
