<a href="https://colab.research.google.com/github/SLCFLAB/Data-Science-Python/blob/main/Day%206/6_2.%20Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ref: https://github.com/Harry24k/Pytorch-Basic

# 2. Autograd

In [1]:
import torch

## 2.1 Autograd 

In [11]:
x = torch.ones(1)
x.requires_grad

False

In [3]:
y = torch.ones(1)
y.requires_grad

False

In [4]:
z = x + y

In [10]:
z.requires_grad

True

In [14]:
x.requires_grad=True
# x.requires_grad_()
x.requires_grad

True

In [19]:
z = x + y

In [20]:
z.requires_grad

True

## 2.2 Backward

In [21]:
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
y

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [22]:
y.sum()

tensor(10., grad_fn=<SumBackward0>)

In [23]:
y.max()

tensor(4., grad_fn=<MaxBackward1>)

In [24]:
z = 2*y + 1
z

tensor([[3., 5.],
        [7., 9.]], grad_fn=<AddBackward0>)

In [25]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)

y.requires_grad : True
z.requires_grad : True

y.grad : None
z.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x7f9529b0f1d0>


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:417.)
  return self._grad


In [26]:
gz = z.grad_fn
print("z.grad_fn :", gz)
print("Where is z.grad_fn?", id(gz))
print("Where is z.grad_fn in hex?", hex(id(gz)))

z.grad_fn : <AddBackward0 object at 0x7f9420e46d90>
Where is z.grad_fn? 140274183728528
Where is z.grad_fn in hex? 0x7f9420e46d90


In [28]:
# grad can be implicitly created only for scalar outputs
z.backward()

RuntimeError: ignored

In [29]:
out = z.sum()
out

tensor(24., grad_fn=<SumBackward0>)

In [30]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)
print("out.requires_grad :", out.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.requires_grad : True
z.requires_grad : True
out.requires_grad : True

y.grad : None
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x7f9420e46d90>
out.grad_fn : <SumBackward0 object at 0x7f9420e9e490>


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:417.)
  return self._grad


In [31]:
out.backward()

In [32]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)
print("out.requires_grad :", out.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.requires_grad : True
z.requires_grad : True
out.requires_grad : True

y.grad : tensor([[2., 2.],
        [2., 2.]])
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x7f9420e46d90>
out.grad_fn : <SumBackward0 object at 0x7f9420e8fb50>


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:417.)
  return self._grad


In [33]:
# By default, gradients are only retained for leaf variables. non-leaf variables
# gradients are not retained to be inspected later. This was done by design, to save memory.
print("y == leaf? : ", y.is_leaf)
print("z == leaf? : ", z.is_leaf)

y == leaf? :  True
z == leaf? :  False


## 2.3 Detach from Autograd & .detach() vs .data

In [ ]:
# Graph 위에 있는 변수는 바로 numpy로 변환할 수 없음.
z.numpy()

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

In [ ]:
# 따라서 .detach와 .data 중 하나를 사용해야함.
z.detach().numpy()

array([[3., 5.],
       [7., 9.]], dtype=float32)

In [ ]:
# 따라서 .detach와 .data 중 하나를 사용해야함.
z.data.numpy()

array([[3., 5.],
       [7., 9.]], dtype=float32)